spring.application.name=api-gateway
server.port=8089

spring.cloud.gateway.routes[0].id=orchestrator-route
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/pipeline/**

spring.cloud.gateway.routes[1].id=planner-route
spring.cloud.gateway.routes[1].uri=http://localhost:8001
spring.cloud.gateway.routes[1].predicates[0]=Path=/plan/**
